name: TriHunt
main: net.trilleo.mc.plugins.trihunt.Main
version: 0.1.0
api-version: 1.21

commands:
  trihunt:
    description: Main command for the TriHunt plugin
    usage: /trihunt <subcommand> [args]
    aliases:
      - th